name: godd
summary: godd is a nice dd replacement
description: |
 godd is a nice improvement over dd as it has nice progress bars and
 knows about target devices and can stream from http and decompress
 on the fly.

 This means it is possible to e.g. install a Ubuntu Core image via
 godd http://cdimage.../ubuntu-core-16-amd64.img.xz /dev/sdc
version: 0.7
confinement: devmode

apps:
  godd:
    command: bin/godd

parts:
  godd:
    plugin: go
    source: .
    go-importpath: github.com/mvo5/godd
    override-build: |
      # the horror the horror
      sudo mv /usr/bin/go /usr/bin/go.system
      sudo ln -s /snap/bin/go /usr/bin/go
      snapcraftctl build
      sudo rm /usr/bin/go
      sudo mv /usr/bin/go.system /usr/bin/go
    build-snaps:
      - go
    prime:
     - bin/godd*
