name: godd
summary: godd is a nice dd replacement
description: |
 godd is a nice improvement over dd as it has nice progress bars and
 knows about target devices
version: 0.2
confinement: devmode

apps:
  godd:
    command: bin/godd

parts:
  godd:
    plugin: go
    source: .
    stage-packages: [libgudev-1.0-dev]
    snap:
     - usr/lib/x86_64-linux-gnu/libgudev-1.0.so*
     - usr/lib/x86_64-linux-gnu/libobject-2.0.so*
     - usr/lib/x86_64-linux-gnu/libglib-2.0.so*
     - bin/godd*
